/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vival
 */
public class ConsultarVenta extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarVenta
     */
    DefaultTableModel modeloTablaConsVenta;
    static String[] cabeceraTablaAlmacen = {"ID", "Cliente", "Fecha", "Total"};
    static String fecha;
    public ConsultarVenta(double total) {
        initComponents();
        fecha = today();
        total = 100;
        String[][] datosPrueba = {{"1","Publico General", fecha, String.valueOf(total)}, {"2","Publico General", fecha, String.valueOf(total)}};
        modeloTablaConsVenta = new DefaultTableModel(datosPrueba, cabeceraTablaAlmacen);
        tablaConsVenta.setModel(modeloTablaConsVenta);
    }
    
    public static String today() {
        Calendar fechaC = Calendar.getInstance();
        return String.valueOf(fechaC.getTime().getDate()) + "/" + 
                String.valueOf(fechaC.getTime().getMonth()+1) + "/" +
                String.valueOf(fechaC.getTime().getYear()+1900);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsVenta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 450));
        getContentPane().setLayout(null);

        tablaConsVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaConsVenta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 0, 450, 410);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta de Ventas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 0, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaConsVenta;
    // End of variables declaration//GEN-END:variables
}
