/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

/**
 *
 * @author pnrv2
 */
public class GestionarProveedores extends javax.swing.JPanel {

    /**
     * Creates new form GestionarProveedores
     */
    public GestionarProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        opcionesPane = new javax.swing.JPanel();
        windowOptions = new javax.swing.JPanel();
        ventanaAgregar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNombreProv = new javax.swing.JTextField();
        errorLabelAgregar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        ventanaConsultar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        errorLabelConsultar = new javax.swing.JLabel();
        tipoConsultaLabel = new javax.swing.JLabel();
        tfIDProv = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        ventanaModificar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        errorLabelModificar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdProvModificar = new javax.swing.JTextField();
        btnBuscarModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfNombreProvModificar = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        ventanaEliminar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        errorLabelEliminar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfIDProvEliminar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfNombreEliminar = new javax.swing.JTextField();
        btnBuscarEliminar = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        cabeceraOpcionesPane = new javax.swing.JPanel();
        tituloOpcionesLabel = new javax.swing.JLabel();
        botonesPane = new javax.swing.JPanel();
        btnAgregarWindow = new javax.swing.JButton();
        btnConsultarWindow = new javax.swing.JButton();
        btnModificarWindow = new javax.swing.JButton();
        btnEliminarWindow = new javax.swing.JButton();
        tituloPrincipalPane = new javax.swing.JPanel();
        tituloPrincipalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        opcionesPane.setLayout(new java.awt.BorderLayout());

        windowOptions.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar Proveedor");

        jLabel4.setText("Nombre:");

        tfNombreProv.setText("Ingrese Nombre del Proveedor");

        errorLabelAgregar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelAgregar.setText("Error Label");

        btnAgregar.setText("Agregar");

        javax.swing.GroupLayout ventanaAgregarLayout = new javax.swing.GroupLayout(ventanaAgregar);
        ventanaAgregar.setLayout(ventanaAgregarLayout);
        ventanaAgregarLayout.setHorizontalGroup(
            ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaAgregarLayout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorLabelAgregar)
                            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfNombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnAgregar)))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ventanaAgregarLayout.setVerticalGroup(
            ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabelAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaAgregar, "Agregar");
        ventanaAgregar.getAccessibleContext().setAccessibleName("");
        ventanaAgregar.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultar Proveedor");

        errorLabelConsultar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelConsultar.setText("Error Label");

        tipoConsultaLabel.setText("ID Proveedor:");

        tfIDProv.setText("Ingrese el ID del Proveedor");
        tfIDProv.setEnabled(false);

        btnBuscar.setText("Buscar");

        btnGroup.add(jRadioButton1);
        jRadioButton1.setText("Todos");

        btnGroup.add(jRadioButton2);
        jRadioButton2.setText("ID");

        btnGroup.add(jRadioButton3);
        jRadioButton3.setText("Nombre");

        jLabel8.setText("Tipo de Consulta:");

        javax.swing.GroupLayout ventanaConsultarLayout = new javax.swing.GroupLayout(ventanaConsultar);
        ventanaConsultar.setLayout(ventanaConsultarLayout);
        ventanaConsultarLayout.setHorizontalGroup(
            ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                        .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3))
                            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel8))
                            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errorLabelConsultar)
                                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                        .addComponent(tipoConsultaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfIDProv, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(btnBuscar)))))))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ventanaConsultarLayout.setVerticalGroup(
            ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addComponent(errorLabelConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoConsultaLabel)
                    .addComponent(tfIDProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaConsultar, "Consultar");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Modificar Proveedor");
        jLabel6.setToolTipText("");

        errorLabelModificar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelModificar.setText("Error Label");

        jLabel2.setText("ID Proveedor:");

        tfIdProvModificar.setText("Ingrese el ID del Proveedor");

        btnBuscarModificar.setText("Buscar");

        jLabel7.setText("Nombre Proveedor:");

        tfNombreProvModificar.setText("Ingrese el nombre del Proveedor");
        tfNombreProvModificar.setEnabled(false);

        btnModificar.setText("Guardar Cambios");
        btnModificar.setEnabled(false);

        javax.swing.GroupLayout ventanaModificarLayout = new javax.swing.GroupLayout(ventanaModificar);
        ventanaModificar.setLayout(ventanaModificarLayout);
        ventanaModificarLayout.setHorizontalGroup(
            ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaModificarLayout.createSequentialGroup()
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaModificarLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnBuscarModificar)
                        .addGap(30, 30, 30)
                        .addComponent(btnModificar)
                        .addGap(39, 62, Short.MAX_VALUE))
                    .addGroup(ventanaModificarLayout.createSequentialGroup()
                        .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventanaModificarLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(errorLabelModificar))
                            .addGroup(ventanaModificarLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNombreProvModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfIdProvModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ventanaModificarLayout.setVerticalGroup(
            ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaModificarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(errorLabelModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdProvModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfNombreProvModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarModificar)
                    .addComponent(btnModificar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaModificar, "Modificar");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Eliminar Proveedor");

        errorLabelEliminar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelEliminar.setText("Error Label");

        jLabel9.setText("ID Proveedor:");

        tfIDProvEliminar.setText("Ingrese el Id del Proveedor");

        jLabel10.setText("Nombre:");

        btnBuscarEliminar.setText("Buscar");

        btnConfirm.setText("Eliminar");
        btnConfirm.setEnabled(false);

        javax.swing.GroupLayout ventanaEliminarLayout = new javax.swing.GroupLayout(ventanaEliminar);
        ventanaEliminar.setLayout(ventanaEliminarLayout);
        ventanaEliminarLayout.setHorizontalGroup(
            ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabelEliminar)
                    .addGroup(ventanaEliminarLayout.createSequentialGroup()
                        .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(btnBuscarEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfIDProvEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(tfNombreEliminar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEliminarLayout.createSequentialGroup()
                                .addComponent(btnConfirm)
                                .addGap(36, 36, 36)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ventanaEliminarLayout.setVerticalGroup(
            ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(errorLabelEliminar)
                .addGap(18, 18, 18)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfIDProvEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarEliminar)
                    .addComponent(btnConfirm))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaEliminar, "card5");

        opcionesPane.add(windowOptions, java.awt.BorderLayout.CENTER);

        cabeceraOpcionesPane.setLayout(new java.awt.BorderLayout());

        tituloOpcionesLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloOpcionesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloOpcionesLabel.setText("OPCIONES");
        tituloOpcionesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cabeceraOpcionesPane.add(tituloOpcionesLabel, java.awt.BorderLayout.NORTH);

        btnAgregarWindow.setText("Agregar");
        botonesPane.add(btnAgregarWindow);

        btnConsultarWindow.setText("Consultar");
        botonesPane.add(btnConsultarWindow);

        btnModificarWindow.setText("Modificar");
        botonesPane.add(btnModificarWindow);

        btnEliminarWindow.setText("Eliminar");
        botonesPane.add(btnEliminarWindow);

        cabeceraOpcionesPane.add(botonesPane, java.awt.BorderLayout.CENTER);

        opcionesPane.add(cabeceraOpcionesPane, java.awt.BorderLayout.NORTH);

        add(opcionesPane, java.awt.BorderLayout.LINE_START);

        tituloPrincipalLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tituloPrincipalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPrincipalLabel.setText("Gestion Proveedores");
        tituloPrincipalLabel.setToolTipText("");
        tituloPrincipalLabel.setAutoscrolls(true);
        tituloPrincipalLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout tituloPrincipalPaneLayout = new javax.swing.GroupLayout(tituloPrincipalPane);
        tituloPrincipalPane.setLayout(tituloPrincipalPaneLayout);
        tituloPrincipalPaneLayout.setHorizontalGroup(
            tituloPrincipalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPrincipalPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPrincipalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        tituloPrincipalPaneLayout.setVerticalGroup(
            tituloPrincipalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPrincipalPaneLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(tituloPrincipalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        add(tituloPrincipalPane, java.awt.BorderLayout.PAGE_START);

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProveedores);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonesPane;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarWindow;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarEliminar;
    private javax.swing.JButton btnBuscarModificar;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnConsultarWindow;
    private javax.swing.JButton btnEliminarWindow;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarWindow;
    private javax.swing.JPanel cabeceraOpcionesPane;
    private javax.swing.JLabel errorLabelAgregar;
    private javax.swing.JLabel errorLabelConsultar;
    private javax.swing.JLabel errorLabelEliminar;
    private javax.swing.JLabel errorLabelModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel opcionesPane;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField tfIDProv;
    private javax.swing.JTextField tfIDProvEliminar;
    private javax.swing.JTextField tfIdProvModificar;
    private javax.swing.JTextField tfNombreEliminar;
    private javax.swing.JTextField tfNombreProv;
    private javax.swing.JTextField tfNombreProvModificar;
    private javax.swing.JLabel tipoConsultaLabel;
    private javax.swing.JLabel tituloOpcionesLabel;
    private javax.swing.JLabel tituloPrincipalLabel;
    private javax.swing.JPanel tituloPrincipalPane;
    private javax.swing.JPanel ventanaAgregar;
    private javax.swing.JPanel ventanaConsultar;
    private javax.swing.JPanel ventanaEliminar;
    private javax.swing.JPanel ventanaModificar;
    private javax.swing.JPanel windowOptions;
    // End of variables declaration//GEN-END:variables
}
