/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author vival
 */
public class GestionarCompras extends javax.swing.JPanel {
    DefaultTableModel modeloTablaCompras;
    static String[] cabeceraTablaCompras = {"ID", "Nombre", "Precio", "Existencia", "Stock", "Unidad de Medida"};
    static String[][] datosTemporalesTablaCompras = {{"1","Pepsi", "20", "10", "10", "Empaquetado"}, {"2","Sabritas", "13", "5", "10", "Empaquetado"}};
    static int tablaComprasSeleccionModificar;
    /**
     * Creates new form GestionarAlmacen
     */
    public GestionarCompras() {
        initComponents();
        btnGroupCompras.add(btnRadioID);
        btnGroupCompras.add(btnRadioNombre);
        btnGroupCompras.add(btnRadioPrecio);
        btnGroupCompras.add(btnRadioCantidad);
        btnGroupCompras.add(btnRadioProveedor);
        
        modeloTablaCompras = new DefaultTableModel(datosTemporalesTablaCompras,cabeceraTablaCompras);
        tablaCompras.setModel(modeloTablaCompras);
        tablaCompras.getTableHeader().setReorderingAllowed(false);
        comprasFormaBase();
        //this.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCompras = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnRadioCantidad = new javax.swing.JRadioButton();
        btnRadioID = new javax.swing.JRadioButton();
        btnRadioNombre = new javax.swing.JRadioButton();
        btnRadioPrecio = new javax.swing.JRadioButton();
        btnRadioProveedor = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtComprasBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnConsultaCompras = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCompras1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1360, 720));
        setPreferredSize(new java.awt.Dimension(1450, 694));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCompras);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 490, 460));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Productos por comprar");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 220, 50));

        btnRadioCantidad.setText("Cantidad");
        add(btnRadioCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, 80, -1));

        btnRadioID.setText("ID");
        add(btnRadioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 50, -1));

        btnRadioNombre.setText("Nombre");
        add(btnRadioNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 70, -1));

        btnRadioPrecio.setText("Precio");
        add(btnRadioPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 160, 60, -1));

        btnRadioProveedor.setText("Proveedor");
        add(btnRadioProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 160, 90, -1));

        jLabel7.setText("Filtrar por:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 90, -1));

        txtComprasBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComprasBuscarActionPerformed(evt);
            }
        });
        add(txtComprasBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 290, 30));

        jLabel8.setText("Buscar");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 70, -1));

        btnConsultaCompras.setText("Consultar compras");
        btnConsultaCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaComprasActionPerformed(evt);
            }
        });
        add(btnConsultaCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("GESTIONAR COMPRAS");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 220, 50));

        tablaCompras1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaCompras1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 490, 450));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Productos disponibles");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 220, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtComprasBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComprasBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComprasBuscarActionPerformed

    private void btnConsultaComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaComprasActionPerformed
        Object[] opciones = new Object[] {};
        //JOptionPane.showOptionDialog(this,"Ingrese la fecha de vencimiento de su tarjeta", JOptionPane.INFORMATION_MESSAGE, JOptionPane.DEFAULT_OPTION, null, opciones, null);
        
        //JOptionPane.showMessageDialog(null, new JScrollPane(tablaCompras));
    }//GEN-LAST:event_btnConsultaComprasActionPerformed

        /*------------------Metodo para regresar a la fomra base el panel almacen------------------------*/
    public void comprasFormaBase() {
        jLabel7.setVisible(true);
        btnRadioID.setVisible(true);
        btnRadioProveedor.setVisible(true);
        btnRadioCantidad.setVisible(true);
        btnRadioNombre.setVisible(true);
        btnRadioPrecio.setVisible(true);
        jLabel8.setVisible(true);
        txtComprasBuscar.setVisible(true);
        
        btnRadioID.setSelected(true);
        txtComprasBuscar.setText("");
        
    }
    /*------------------Metodo para poner visible los txt y labels para editar los productos del panel almacen------------------------*/
    public void almacenEditable() {

    }
    /*------------------Metodo para Comprobar si los textos estan vacios del panel almecen------------------------*/
   /* public boolean comprobarTXTAlmacen() {
        return !txtStock.getText().equals("")
                && !txtPrecio.getText().equals("") && !txtExistencia.getText().equals("") && !txtNombre.getText().equals("");
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaCompras;
    private javax.swing.ButtonGroup btnGroupCompras;
    private javax.swing.JRadioButton btnRadioCantidad;
    private javax.swing.JRadioButton btnRadioID;
    private javax.swing.JRadioButton btnRadioNombre;
    private javax.swing.JRadioButton btnRadioPrecio;
    private javax.swing.JRadioButton btnRadioProveedor;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTable tablaCompras1;
    private javax.swing.JTextField txtComprasBuscar;
    // End of variables declaration//GEN-END:variables
}
