/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

/**
 *
 * @author pnrv2
 */
public class GestionarProveedores extends javax.swing.JPanel {

    private boolean queryTodos;
    private boolean queryId;
    private boolean queryNom;
    /**
     * Creates new form GestionarProveedores
     */
    public GestionarProveedores() {
        queryTodos = false;
        queryId = false;
        queryNom = false;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        opcionesPane = new javax.swing.JPanel();
        windowOptions = new javax.swing.JPanel();
        ventanaAgregar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNombreProv = new javax.swing.JTextField();
        errorLabelAgregar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        ventanaConsultar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        errorLabelConsultar = new javax.swing.JLabel();
        tipoConsultaLabel = new javax.swing.JLabel();
        tfIDProv = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jrbTodos = new javax.swing.JRadioButton();
        jrbID = new javax.swing.JRadioButton();
        jrbNombre = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        ventanaModificar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        errorLabelModificar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdProvModificar = new javax.swing.JTextField();
        btnBuscarModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfNombreProvModificar = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        ventanaEliminar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        errorLabelEliminar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfIDProvEliminar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfNombreEliminar = new javax.swing.JTextField();
        btnBuscarEliminar = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        cabeceraOpcionesPane = new javax.swing.JPanel();
        tituloOpcionesLabel = new javax.swing.JLabel();
        botonesPane = new javax.swing.JPanel();
        btnAgregarWindow = new javax.swing.JButton();
        btnConsultarWindow = new javax.swing.JButton();
        btnModificarWindow = new javax.swing.JButton();
        btnEliminarWindow = new javax.swing.JButton();
        tituloPrincipalPane = new javax.swing.JPanel();
        tituloPrincipalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        opcionesPane.setLayout(new java.awt.BorderLayout());

        windowOptions.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar Proveedor");

        jLabel4.setText("Nombre:");

        tfNombreProv.setText("Ingrese Nombre del Proveedor");
        tfNombreProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNombreProvMouseClicked(evt);
            }
        });

        errorLabelAgregar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelAgregar.setText("Error Label");

        btnAgregar.setText("Agregar");

        javax.swing.GroupLayout ventanaAgregarLayout = new javax.swing.GroupLayout(ventanaAgregar);
        ventanaAgregar.setLayout(ventanaAgregarLayout);
        ventanaAgregarLayout.setHorizontalGroup(
            ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaAgregarLayout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorLabelAgregar)
                            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnAgregar))
                            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfNombreProv, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ventanaAgregarLayout.setVerticalGroup(
            ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabelAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNombreProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaAgregar, "Agregar");
        ventanaAgregar.getAccessibleContext().setAccessibleName("");
        ventanaAgregar.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultar Proveedor");

        errorLabelConsultar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelConsultar.setText("Error Label");

        tipoConsultaLabel.setText("ID Proveedor:");

        tfIDProv.setText("Ingrese el ID del Proveedor");
        tfIDProv.setEnabled(false);
        tfIDProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfIDProvMouseClicked(evt);
            }
        });

        btnBuscar.setText("Buscar");

        btnGroup.add(jrbTodos);
        jrbTodos.setText("Todos");
        jrbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTodosActionPerformed(evt);
            }
        });

        btnGroup.add(jrbID);
        jrbID.setText("ID");
        jrbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIDActionPerformed(evt);
            }
        });

        btnGroup.add(jrbNombre);
        jrbNombre.setText("Nombre");
        jrbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNombreActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo de Consulta:");

        javax.swing.GroupLayout ventanaConsultarLayout = new javax.swing.GroupLayout(ventanaConsultar);
        ventanaConsultar.setLayout(ventanaConsultarLayout);
        ventanaConsultarLayout.setHorizontalGroup(
            ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                        .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel8))
                            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errorLabelConsultar)
                                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                        .addComponent(tipoConsultaLabel)
                                        .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(btnBuscar))
                                            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfIDProv, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(32, 32, 32)))
                .addContainerGap())
            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jrbTodos)
                .addGap(18, 18, 18)
                .addComponent(jrbID)
                .addGap(18, 18, 18)
                .addComponent(jrbNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventanaConsultarLayout.setVerticalGroup(
            ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbTodos)
                    .addComponent(jrbID)
                    .addComponent(jrbNombre))
                .addGap(18, 18, 18)
                .addComponent(errorLabelConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoConsultaLabel)
                    .addComponent(tfIDProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaConsultar, "Consultar");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Modificar Proveedor");
        jLabel6.setToolTipText("");

        errorLabelModificar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelModificar.setText("Error Label");

        jLabel2.setText("ID Proveedor:");

        tfIdProvModificar.setText("Ingrese el ID del Proveedor");
        tfIdProvModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfIdProvModificarMouseClicked(evt);
            }
        });

        btnBuscarModificar.setText("Buscar");
        btnBuscarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarModificarActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre Proveedor:");

        tfNombreProvModificar.setText("Ingrese el nombre del Proveedor");
        tfNombreProvModificar.setEnabled(false);
        tfNombreProvModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNombreProvModificarMouseClicked(evt);
            }
        });

        btnModificar.setText("Guardar Cambios");
        btnModificar.setEnabled(false);

        javax.swing.GroupLayout ventanaModificarLayout = new javax.swing.GroupLayout(ventanaModificar);
        ventanaModificar.setLayout(ventanaModificarLayout);
        ventanaModificarLayout.setHorizontalGroup(
            ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaModificarLayout.createSequentialGroup()
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaModificarLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnBuscarModificar)
                        .addGap(30, 30, 30)
                        .addComponent(btnModificar)
                        .addGap(39, 62, Short.MAX_VALUE))
                    .addGroup(ventanaModificarLayout.createSequentialGroup()
                        .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventanaModificarLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(errorLabelModificar))
                            .addGroup(ventanaModificarLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNombreProvModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(tfIdProvModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ventanaModificarLayout.setVerticalGroup(
            ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaModificarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(errorLabelModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdProvModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfNombreProvModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarModificar)
                    .addComponent(btnModificar))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaModificar, "Modificar");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Eliminar Proveedor");

        errorLabelEliminar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelEliminar.setText("Error Label");

        jLabel9.setText("ID Proveedor:");

        tfIDProvEliminar.setText("Ingrese el Id del Proveedor");
        tfIDProvEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfIDProvEliminarMouseClicked(evt);
            }
        });

        jLabel10.setText("Nombre:");

        tfNombreEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNombreEliminarMouseClicked(evt);
            }
        });

        btnBuscarEliminar.setText("Buscar");
        btnBuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEliminarActionPerformed(evt);
            }
        });

        btnConfirm.setText("Eliminar");
        btnConfirm.setEnabled(false);

        javax.swing.GroupLayout ventanaEliminarLayout = new javax.swing.GroupLayout(ventanaEliminar);
        ventanaEliminar.setLayout(ventanaEliminarLayout);
        ventanaEliminarLayout.setHorizontalGroup(
            ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabelEliminar)
                    .addGroup(ventanaEliminarLayout.createSequentialGroup()
                        .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(btnBuscarEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfIDProvEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(tfNombreEliminar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEliminarLayout.createSequentialGroup()
                                .addComponent(btnConfirm)
                                .addGap(36, 36, 36)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ventanaEliminarLayout.setVerticalGroup(
            ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(errorLabelEliminar)
                .addGap(18, 18, 18)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfIDProvEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarEliminar)
                    .addComponent(btnConfirm))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaEliminar, "Eliminar");

        opcionesPane.add(windowOptions, java.awt.BorderLayout.CENTER);

        cabeceraOpcionesPane.setLayout(new java.awt.BorderLayout());

        tituloOpcionesLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloOpcionesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloOpcionesLabel.setText("OPCIONES");
        tituloOpcionesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cabeceraOpcionesPane.add(tituloOpcionesLabel, java.awt.BorderLayout.NORTH);

        btnAgregarWindow.setText("Agregar");
        btnAgregarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnAgregarWindow);

        btnConsultarWindow.setText("Consultar");
        btnConsultarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnConsultarWindow);

        btnModificarWindow.setText("Modificar");
        btnModificarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnModificarWindow);

        btnEliminarWindow.setText("Eliminar");
        btnEliminarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnEliminarWindow);

        cabeceraOpcionesPane.add(botonesPane, java.awt.BorderLayout.CENTER);

        opcionesPane.add(cabeceraOpcionesPane, java.awt.BorderLayout.NORTH);

        add(opcionesPane, java.awt.BorderLayout.LINE_START);

        tituloPrincipalLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tituloPrincipalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPrincipalLabel.setText("Gestion Proveedores");
        tituloPrincipalLabel.setToolTipText("");
        tituloPrincipalLabel.setAutoscrolls(true);
        tituloPrincipalLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout tituloPrincipalPaneLayout = new javax.swing.GroupLayout(tituloPrincipalPane);
        tituloPrincipalPane.setLayout(tituloPrincipalPaneLayout);
        tituloPrincipalPaneLayout.setHorizontalGroup(
            tituloPrincipalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPrincipalPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPrincipalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addContainerGap())
        );
        tituloPrincipalPaneLayout.setVerticalGroup(
            tituloPrincipalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPrincipalPaneLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(tituloPrincipalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        add(tituloPrincipalPane, java.awt.BorderLayout.PAGE_START);

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProveedores);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();
        card.show(windowOptions, "Agregar");
    }//GEN-LAST:event_btnAgregarWindowActionPerformed

    private void btnConsultarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();
        card.show(windowOptions, "Consultar");
    }//GEN-LAST:event_btnConsultarWindowActionPerformed

    private void btnModificarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();
        card.show(windowOptions, "Modificar");
    }//GEN-LAST:event_btnModificarWindowActionPerformed

    private void btnEliminarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();
        card.show(windowOptions, "Eliminar");
    }//GEN-LAST:event_btnEliminarWindowActionPerformed

    private void tfNombreProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNombreProvMouseClicked
        tfNombreProv.setText("");
    }//GEN-LAST:event_tfNombreProvMouseClicked

    private void jrbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTodosActionPerformed
        queryTodos = true;
        queryId = false;
        queryNom = false;
        tfIDProv.setEnabled(false);
    }//GEN-LAST:event_jrbTodosActionPerformed

    private void jrbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIDActionPerformed
        queryId = true;
        queryTodos = false;
        queryNom = false;
        tfIDProv.setEnabled(true);
        tipoConsultaLabel.setText("ID Proveedor:");
    }//GEN-LAST:event_jrbIDActionPerformed

    private void jrbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNombreActionPerformed
        queryNom = true;
        queryId = false;
        queryTodos = false;
        tfIDProv.setEnabled(true);
        tipoConsultaLabel.setText("Nombre Proveedor:");
    }//GEN-LAST:event_jrbNombreActionPerformed

    private void tfIDProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfIDProvMouseClicked
        tfIDProv.setText("");
    }//GEN-LAST:event_tfIDProvMouseClicked

    private void tfIdProvModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfIdProvModificarMouseClicked
        tfIdProvModificar.setText("");
    }//GEN-LAST:event_tfIdProvModificarMouseClicked

    private void btnBuscarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarModificarActionPerformed
        //metodos de busqueda en la base de datos
    }//GEN-LAST:event_btnBuscarModificarActionPerformed

    private void tfNombreProvModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNombreProvModificarMouseClicked
        tfNombreProv.setText("");
    }//GEN-LAST:event_tfNombreProvModificarMouseClicked

    private void tfIDProvEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfIDProvEliminarMouseClicked
        tfIDProvEliminar.setText("");
    }//GEN-LAST:event_tfIDProvEliminarMouseClicked

    private void tfNombreEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNombreEliminarMouseClicked
        tfNombreEliminar.setText("");
    }//GEN-LAST:event_tfNombreEliminarMouseClicked

    private void btnBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarActionPerformed
        //metodos de busqueda en la base de datos
    }//GEN-LAST:event_btnBuscarEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonesPane;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarWindow;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarEliminar;
    private javax.swing.JButton btnBuscarModificar;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnConsultarWindow;
    private javax.swing.JButton btnEliminarWindow;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarWindow;
    private javax.swing.JPanel cabeceraOpcionesPane;
    private javax.swing.JLabel errorLabelAgregar;
    private javax.swing.JLabel errorLabelConsultar;
    private javax.swing.JLabel errorLabelEliminar;
    private javax.swing.JLabel errorLabelModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbID;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JRadioButton jrbTodos;
    private javax.swing.JPanel opcionesPane;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField tfIDProv;
    private javax.swing.JTextField tfIDProvEliminar;
    private javax.swing.JTextField tfIdProvModificar;
    private javax.swing.JTextField tfNombreEliminar;
    private javax.swing.JTextField tfNombreProv;
    private javax.swing.JTextField tfNombreProvModificar;
    private javax.swing.JLabel tipoConsultaLabel;
    private javax.swing.JLabel tituloOpcionesLabel;
    private javax.swing.JLabel tituloPrincipalLabel;
    private javax.swing.JPanel tituloPrincipalPane;
    private javax.swing.JPanel ventanaAgregar;
    private javax.swing.JPanel ventanaConsultar;
    private javax.swing.JPanel ventanaEliminar;
    private javax.swing.JPanel ventanaModificar;
    private javax.swing.JPanel windowOptions;
    // End of variables declaration//GEN-END:variables
}
