/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

/**
 *
 * @author pnrv2
 */
import java.awt.Color;
import javax.swing.border.Border;
import javax.swing.JComponent;
import javax.swing.plaf.basic.BasicBorders;

public class IngresoDialog extends javax.swing.JDialog {
    
    private Border[] bordes;
    
    private String user = "Admin";
    private String password = "12345";
    
    private boolean successLogIn;
    /**
     * Creates new form IngresoDialog
     */
    public IngresoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        successLogIn = false;
        bordes = new Border[2];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        errorLogIn = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        fieldUser = new javax.swing.JTextField();
        fieldPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log In");
        setLocation((int) ((java.awt.Toolkit.getDefaultToolkit().getScreenSize().getWidth()-403)/2), (int) ((java.awt.Toolkit.getDefaultToolkit().getScreenSize().getHeight()-256)/2));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Abarrotes Valdivia");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Contraseña:");

        errorLogIn.setForeground(new java.awt.Color(255, 0, 0));

        btnLogIn.setText("Ingresar");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        fieldUser.setText("Ingrese su usuario");
        fieldUser.setFocusable(false);
        fieldUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldUserMouseClicked(evt);
            }
        });

        fieldPass.setText("Ingrese su contraseña");
        fieldPass.setToolTipText("");
        fieldPass.setFocusable(false);
        fieldPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldPassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldUser)
                            .addComponent(errorLogIn)
                            .addComponent(fieldPass, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogIn)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(errorLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnLogIn)
                .addGap(14, 14, 14))
        );

        fieldPass.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldUserMouseClicked
        fieldUser.setBorder(bordes[0]);
        fieldUser.setFocusable(true);
        fieldUser.setText("");
        fieldPass.setFocusable(true);
        errorLogIn.setText("");
    }//GEN-LAST:event_fieldUserMouseClicked

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        bordes[0] = fieldUser.getBorder();
        bordes[1] = fieldPass.getBorder();
        
        String inputFieldUser = fieldUser.getText();
        String inputFieldPass = String.valueOf(fieldPass.getPassword());
        if(inputFieldUser.equals(user) && inputFieldPass.equals(password)){
            Main.successLogIn = true;
            this.dispose();
        }else{
            fieldUser.setBorder(new BasicBorders.FieldBorder(Color.RED, Color.RED, Color.RED, Color.RED));
            fieldPass.setBorder(new BasicBorders.FieldBorder(Color.RED, Color.RED, Color.RED, Color.RED));
            errorLogIn.setText("El usuario o contraseña son incorrectos");
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Main.terminarPrograma();
    }//GEN-LAST:event_formWindowClosing

    private void fieldPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPassMouseClicked
        fieldPass.setBorder(bordes[1]);
        fieldPass.setText("");
    }//GEN-LAST:event_fieldPassMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel errorLogIn;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
